# https://docs.travis-ci.com/user/languages/go/
language: go
sudo: false
go:
  - 1.8
  - 1.7
  - 1.6
matrix:
  fast_finish: true
  allow_failures:
    - go: 1.7
    - go: 1.6
before_install:
  - go get github.com/satori/go.uuid
